### ISSUE TITLE
passing objects between a code chunk and an exercise

### ISSUE THREAD

**Issue by LaurenDahlin** [rstudio/rtutor#66]
I need to be able to load data (from a csv in the www directory) in a code chunk and have the data object accessible within an exercise. More generally, however, I can't figure out how to make objects accessible in an exercise. Very simple example below (quotes taken out so code will show on github). Help much appreciated.

```
---
title: "Tutorial"
output: rtutor::tutorial
runtime: shiny_prerendered
---

[triple quote]{r setup, include=FALSE}
library(rtutor)
knitr::opts_chunk$set(echo = FALSE)
[triple quote]


[triple quote]{r loadData}

x <- c(1,2,3,4,5 / 6, 7, 8, 9, 10)

[triple quote]

[triple quote]{r view-data, exercise=TRUE, exercise.eval=TRUE}


[triple quote]

[triple quote]{r view-data-hint}
x
[triple quote]

```

**Comment by dtkaplan** [comment]
I've been creating shared chunks to coordinate between the knitr part of the document and the environment in which the exercises are defined.

1) create a setup chunk to be used in the exercises, before where the corresponding content in the knitr'ed part of the document occurs.
2) In an ordinary chunk --- that is, not an exercise --- refer to the chunk in (1) using `ref.label=`.
3) In an exercise chunk, refer to the chunk in (1) using `exercise.setup =`.

**Comment by LaurenDahlin** [comment]
This worked perfectly. Thank you!
