### ISSUE TITLE
. in header seems to break progressive reveal

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rtutor#67]
In the example document below, you can click through to `### Subtopic 2.` but not past it. At that point, clicking the "Continue" button does nothing. The issue resolves if you take the period out of the header and re-run.

````
---
title: "Exploratory Data Analysis"
output: 
  rtutor::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(rtutor)
```

## Section 1

### Subtopic 1

text

### Subtopic 2.

text

### Subtopic 3

text

````

I expect users will run into this from time to time with headers like `### Quality vs. Quantity`.

**Comment by jjallaire** [comment]
@robbyshaver Any idea what might be happening here?

**Comment by robbyshaver** [comment]
The console show an error down in ShinyApp. In tutor.js at line 247, we're firing a progress event for the sectionId (which correctly has a period in it).

  Shiny.addCustomMessageHandler("tutor.progress_event", function(progress) {
    thiz.$fireProgressEvent(progress.event, progress.data);
  });

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rtutor/commit/2462b81a05fd1822e2ba7ff7c6554ce550e28deb
